name: Arduino Compilation Test
on: 
  - push
  - pull_request
  - workflow_dispatch
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the Smartie Sorter repository
       uses: actions/checkout@v6 
       
     - name: Test whether the Arduino sketches compile successfully
       uses: arduino/compile-sketches@v1
       with:
         fqbn: arduino:avr:nano
         sketch-paths: |
           - smartie_sorter
           - enclosure_code
           - management
         libraries: |
           # No libraries are required
           -

