name: Arduino Compilation Test
on: 
  - push
  - workflow_dispatch
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6 
     - uses: arduino/compile-sketches@v1
       with:
         fqbn: arduino:avr:nano
         sketch_paths: |
           - ./
         libraries: |
           # No libraries are required
           -

